// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Fingrid.API.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DatasetType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "timeseries")]
        #pragma warning disable CS1591
        Timeseries,
        #pragma warning restore CS1591
        [EnumMember(Value = "file")]
        #pragma warning disable CS1591
        File,
        #pragma warning restore CS1591
    }
}
