// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace Fingrid.API.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum DatasetFormat
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "csv")]
        #pragma warning disable CS1591
        Csv,
        #pragma warning restore CS1591
        [EnumMember(Value = "json")]
        #pragma warning disable CS1591
        Json,
        #pragma warning restore CS1591
        [EnumMember(Value = "app")]
        #pragma warning disable CS1591
        App,
        #pragma warning restore CS1591
        [EnumMember(Value = "7zip")]
        #pragma warning disable CS1591
        Sevenzip,
        #pragma warning restore CS1591
        [EnumMember(Value = "zip")]
        #pragma warning disable CS1591
        Zip,
        #pragma warning restore CS1591
        [EnumMember(Value = "xlsx")]
        #pragma warning disable CS1591
        Xlsx,
        #pragma warning restore CS1591
        [EnumMember(Value = "xml")]
        #pragma warning disable CS1591
        Xml,
        #pragma warning restore CS1591
    }
}
