// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Fingrid.API.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class HealthStatus : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The app property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Fingrid.API.Models.StatusResponse? App { get; set; }
#nullable restore
#else
        public global::Fingrid.API.Models.StatusResponse App { get; set; }
#endif
        /// <summary>The database property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Fingrid.API.Models.StatusResponse? Database { get; set; }
#nullable restore
#else
        public global::Fingrid.API.Models.StatusResponse Database { get; set; }
#endif
        /// <summary>The network property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::Fingrid.API.Models.StatusResponse? Network { get; set; }
#nullable restore
#else
        public global::Fingrid.API.Models.StatusResponse Network { get; set; }
#endif
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Fingrid.API.Models.HealthStatus"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Fingrid.API.Models.HealthStatus CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Fingrid.API.Models.HealthStatus();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "app", n => { App = n.GetObjectValue<global::Fingrid.API.Models.StatusResponse>(global::Fingrid.API.Models.StatusResponse.CreateFromDiscriminatorValue); } },
                { "database", n => { Database = n.GetObjectValue<global::Fingrid.API.Models.StatusResponse>(global::Fingrid.API.Models.StatusResponse.CreateFromDiscriminatorValue); } },
                { "network", n => { Network = n.GetObjectValue<global::Fingrid.API.Models.StatusResponse>(global::Fingrid.API.Models.StatusResponse.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::Fingrid.API.Models.StatusResponse>("app", App);
            writer.WriteObjectValue<global::Fingrid.API.Models.StatusResponse>("database", Database);
            writer.WriteObjectValue<global::Fingrid.API.Models.StatusResponse>("network", Network);
        }
    }
}
#pragma warning restore CS0618
