// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace Fingrid.API.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class Notification : IParsable
    #pragma warning restore CS1591
    {
        /// <summary>The endTimeUtc property</summary>
        public DateTimeOffset? EndTimeUtc { get; set; }
        /// <summary>The id property</summary>
        public double? Id { get; set; }
        /// <summary>The linkEn property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LinkEn { get; set; }
#nullable restore
#else
        public string LinkEn { get; set; }
#endif
        /// <summary>The linkFi property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LinkFi { get; set; }
#nullable restore
#else
        public string LinkFi { get; set; }
#endif
        /// <summary>The linkTextEn property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LinkTextEn { get; set; }
#nullable restore
#else
        public string LinkTextEn { get; set; }
#endif
        /// <summary>The linkTextFi property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? LinkTextFi { get; set; }
#nullable restore
#else
        public string LinkTextFi { get; set; }
#endif
        /// <summary>The messageEn property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessageEn { get; set; }
#nullable restore
#else
        public string MessageEn { get; set; }
#endif
        /// <summary>The messageFi property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? MessageFi { get; set; }
#nullable restore
#else
        public string MessageFi { get; set; }
#endif
        /// <summary>The modifiedAtUtc property</summary>
        public DateTimeOffset? ModifiedAtUtc { get; set; }
        /// <summary>The startTimeUtc property</summary>
        public DateTimeOffset? StartTimeUtc { get; set; }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::Fingrid.API.Models.Notification"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::Fingrid.API.Models.Notification CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::Fingrid.API.Models.Notification();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "endTimeUtc", n => { EndTimeUtc = n.GetDateTimeOffsetValue(); } },
                { "id", n => { Id = n.GetDoubleValue(); } },
                { "linkEn", n => { LinkEn = n.GetStringValue(); } },
                { "linkFi", n => { LinkFi = n.GetStringValue(); } },
                { "linkTextEn", n => { LinkTextEn = n.GetStringValue(); } },
                { "linkTextFi", n => { LinkTextFi = n.GetStringValue(); } },
                { "messageEn", n => { MessageEn = n.GetStringValue(); } },
                { "messageFi", n => { MessageFi = n.GetStringValue(); } },
                { "modifiedAtUtc", n => { ModifiedAtUtc = n.GetDateTimeOffsetValue(); } },
                { "startTimeUtc", n => { StartTimeUtc = n.GetDateTimeOffsetValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteDateTimeOffsetValue("endTimeUtc", EndTimeUtc);
            writer.WriteDoubleValue("id", Id);
            writer.WriteStringValue("linkEn", LinkEn);
            writer.WriteStringValue("linkFi", LinkFi);
            writer.WriteStringValue("linkTextEn", LinkTextEn);
            writer.WriteStringValue("linkTextFi", LinkTextFi);
            writer.WriteStringValue("messageEn", MessageEn);
            writer.WriteStringValue("messageFi", MessageFi);
            writer.WriteDateTimeOffsetValue("modifiedAtUtc", ModifiedAtUtc);
            writer.WriteDateTimeOffsetValue("startTimeUtc", StartTimeUtc);
        }
    }
}
#pragma warning restore CS0618
